version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"    # Port for accessing the Mini API
      - "9001:9001"    # Port for the MinIO web console
    env_file:
      - s3-login.env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
