CREATE TABLE File
(
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    minio_path VARCHAR(255) NOT NULL,
    folder_id  INTEGER,

    CONSTRAINT fk_folder
        FOREIGN KEY (folder_id)
            REFERENCES folder (id)
            ON DELETE CASCADE
)